/**
部门信息表
 */
CREATE TABLE dept_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL ,
  REMARK VARCHAR(300) DEFAULT NULL ,
  PRIMARY KEY (ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

/**
职位信息表
 */
CREATE TABLE job_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL ,
  REMARK VARCHAR(300) DEFAULT NULL ,
  PRIMARY KEY (ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

/**
用户信息表
 */
CREATE TABLE user_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(20) NOT NULL ,
  PASSWORD VARCHAR(16) NOT NULL ,
  STATUS INT(11) NOT NULL DEFAULT '1',
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_NAME VARCHAR(20) DEFAULT NULL ,
  PRIMARY KEY (ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

/**
员工信息表
 */
CREATE TABLE employee_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  DEPT_ID INT(11) NOT NULL ,
  JOB_ID INT(11) NOT NULL ,
  NAME VARCHAR(20) NOT NULL ,
  CARD_ID VARCHAR(18) NOT NULL ,
  ADDRESS VARCHAR(50) NOT NULL ,
  POST_CODE VARCHAR(50) DEFAULT NULL ,
  TEL VARCHAR(16) DEFAULT NULL ,
  PHONE VARCHAR(11) NOT NULL ,
  QQ_NUM VARCHAR(10) DEFAULT NULL ,
  EMAIL VARCHAR(50) NOT NULL ,
  SEX INT(11) NOT NULL DEFAULT '1',
  PARTY VARCHAR(10) DEFAULT NULL ,
  BIRTHDAY DATETIME DEFAULT NULL ,
  RECE VARCHAR(100) DEFAULT NULL ,
  EDUCATION VARCHAR(10) DEFAULT NULL ,
  SPECIALITY VARCHAR(20) DEFAULT NULL ,
  HOBBY VARCHAR(100) DEFAULT NULL ,
  REMARK VARCHAR(500) DEFAULT NULL ,
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY FK_EMP_DEPT(DEPT_ID),
  KEY FK_EMP_JOB(JOB_ID),
  CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES dept_info(ID),
  CONSTRAINT FK_EMP_JOB FOREIGN KEY (JOB_ID) REFERENCES job_info(ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

/**
公告信息表
 */
CREATE TABLE notice_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(50) NOT NULL ,
  CONTENT TEXT NOT NULL ,
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ID INT(11) DEFAULT NULL ,
  PRIMARY KEY (ID),
  KEY FK_NOTICE_USER (USER_ID),
  CONSTRAINT FK_NOTICE_USER FOREIGN KEY(USER_ID) REFERENCES user_info(ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

/**
文件信息表
 */
CREATE TABLE document_info(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(50) NOT NULL ,
  FILE_NAME VARCHAR(300) NOT NULL ,
  REAMRK VARCHAR(300) DEFAULT NULL ,
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ID INT(11) DEFAULT NULL ,
  PRIMARY KEY (ID),
  KEY FK_DOCUMENT_USER (USER_ID),
  CONSTRAINT FK_DOCUMENT_USER FOREIGN KEY (USER_ID) REFERENCES user_info(ID)
)ENGINE = INNODB DEFAULT CHARSET = utf8;